apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  hostname: MzQuNDYuMTIuMTU3  # base64 for "127.0.0.1"
  username: cG9zdGdyZXM=  # base64 for "postgres"
  password: cG9zdGdyZXM=  # base64 for "postgres"
  database: cG9zdGdyZXM=  # base64 for "postgres"
  port: NTQzMg==          # base64 for "6543"
